// <auto-generated />
using System;
using Labb_2___LINQ___Lukas_Rose_SUT21.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Labb_2___LINQ___Lukas_Rose_SUT21.Migrations
{
    [DbContext(typeof(Labb2DbContext))]
    [Migration("20220306131356_KlassEdit2")]
    partial class KlassEdit2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Labb_2___LINQ___Lukas_Rose_SUT21.Models.Klass", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KlassNamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Klasser");
                });

            modelBuilder.Entity("Labb_2___LINQ___Lukas_Rose_SUT21.Models.Lärare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FNamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LNamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Lärare");
                });

            modelBuilder.Entity("Labb_2___LINQ___Lukas_Rose_SUT21.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KlassID")
                        .HasColumnType("int");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KlassID");

                    b.ToTable("Studenter");
                });

            modelBuilder.Entity("Labb_2___LINQ___Lukas_Rose_SUT21.Models.Ämne", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KlassID")
                        .HasColumnType("int");

                    b.Property<int?>("LärareID")
                        .HasColumnType("int");

                    b.Property<string>("ÄmnesNamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("KlassID");

                    b.HasIndex("LärareID");

                    b.ToTable("Ämnen");
                });

            modelBuilder.Entity("Labb_2___LINQ___Lukas_Rose_SUT21.Models.Student", b =>
                {
                    b.HasOne("Labb_2___LINQ___Lukas_Rose_SUT21.Models.Klass", null)
                        .WithMany("Elever")
                        .HasForeignKey("KlassID");
                });

            modelBuilder.Entity("Labb_2___LINQ___Lukas_Rose_SUT21.Models.Ämne", b =>
                {
                    b.HasOne("Labb_2___LINQ___Lukas_Rose_SUT21.Models.Klass", null)
                        .WithMany("Ämnen")
                        .HasForeignKey("KlassID");

                    b.HasOne("Labb_2___LINQ___Lukas_Rose_SUT21.Models.Lärare", null)
                        .WithMany("Ämnen")
                        .HasForeignKey("LärareID");
                });
#pragma warning restore 612, 618
        }
    }
}
